apiVersion: v1
kind: ConfigMap
metadata:
  name: loja-veloz-config
  namespace: loja-veloz
data:
  # URLs internas via service discovery do Kubernetes (DNS interno)
  PEDIDOS_URL: "http://pedidos.loja-veloz.svc.cluster.local:8000"
  PAGAMENTOS_URL: "http://pagamentos.loja-veloz.svc.cluster.local:8000"
  ESTOQUE_URL: "http://estoque.loja-veloz.svc.cluster.local:8000"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.observability.svc.cluster.local:4318"
  RABBITMQ_HOST: "rabbitmq.loja-veloz.svc.cluster.local"
  POSTGRES_HOST: "postgres.loja-veloz.svc.cluster.local"
